In [10]:
import numpy as np

# Define the objective function (replace this with your actual loss function)
def objective_function(x):
    return np.sum(x**2)  # Example quadratic function

# Define the gradient of the objective function (replace this with your actual gradient)
def gradient(x):
    return 2 * x

# Bisection Line Search
def bisection_line_search(obj_fn, x, direction, alpha=0.01, beta=0.9, max_iterations=100):
    a = 0
    b = np.inf

    for _ in range(max_iterations):
        midpoint = (a + b) / 2
        left_point = obj_fn(x + midpoint * direction)
        right_point = obj_fn(x + b * direction)
        
        if left_point > right_point:
            a = midpoint
        else:
            b = b * beta
        
        if (b - a) < alpha:
            break
    
    return (a + b) / 2

# Golden Section Line Search
def golden_section_line_search(obj_fn, x, direction, alpha=0.01, max_iterations=100):
    phi = (1 + np.sqrt(5)) / 2
    a = 0
    b = np.inf

    for _ in range(max_iterations):
        c = b - (b - a) / phi
        d = a + (b - a) / phi

        if obj_fn(x + c * direction) > obj_fn(x + d * direction):
            a = c
        else:
            b = d
        
        if (b - a) < alpha:
            break
    
    return (a + b) / 2

# Armijo Rule Line Search
def armijo_line_search(obj_fn, gradient_fn, x, direction, alpha=0.01, beta=0.5, max_iterations=100):
    t = 1.0

    for _ in range(max_iterations):
        if obj_fn(x + t * direction) <= obj_fn(x) + alpha * t * np.dot(gradient_fn(x), direction):
            break
        t *= beta
    
    return t

# Initial point
initial_x = np.zeros([1,2], )  # Initialize with zeros
direction = -gradient(initial_x)

# Perform line search using each method
bisection_result = bisection_line_search(objective_function, initial_x, direction)
golden_section_result = golden_section_line_search(objective_function, initial_x, direction)
armijo_result = armijo_line_search(objective_function, gradient, initial_x, direction)

print("Bisection Line Search Result:", bisection_result)
print("Golden Section Line Search Result:", golden_section_result)
print("Armijo Line Search Result:", armijo_result)


C:\Users\admin\AppData\Local\Temp\ipykernel_55752\4038761674.py:18: RuntimeWarning: invalid value encountered in multiply
  left_point = obj_fn(x + midpoint * direction)
C:\Users\admin\AppData\Local\Temp\ipykernel_55752\4038761674.py:19: RuntimeWarning: invalid value encountered in multiply
  right_point = obj_fn(x + b * direction)
C:\Users\admin\AppData\Local\Temp\ipykernel_55752\4038761674.py:38: RuntimeWarning: invalid value encountered in double_scalars
  c = b - (b - a) / phi
C:\Users\admin\AppData\Local\Temp\ipykernel_55752\4038761674.py:41: RuntimeWarning: invalid value encountered in multiply
  if obj_fn(x + c * direction) > obj_fn(x + d * direction):


ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

In [4]:
import numpy as geek
 
b = geek.zeros(2, dtype = int)
print("Matrix b : \n", b)
 
a = geek.zeros([2, 2], dtype = int)
print("\nMatrix a : \n", a)
 
c = geek.zeros([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
